# Generated by Django 4.2.5 on 2023-09-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_category_photo_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
